name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - master
  workflow_dispatch:

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Smee
        run: |
          curl -X POST https://smee.io/La4pXqk6z2qJ3RuW \
          -H "Content-Type: application/json" \
          -d '{"from":"github-actions"}'
